remote_theme: pmarsceill/just-the-docs
color_scheme: dark
permalink: pretty

# Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/just-the-docs/just-the-docs"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
